# syntax=docker/dockerfile:1
# check=skip=FromPlatformFlagConstDisallowed
#
# The check directive above silences the BuildKit lint warning about the
# pinned --platform on the FROM line. The pin is deliberate: the rocker base
# image is published for linux/amd64 only, so there is no second architecture
# to build for, and fixing the platform is what makes the environment
# reproducible across machines.
#
# Reproducible environment for the population-genetics workflow of
# Melampsora larici-populina (microsatellite markers).
#
#   Build:  docker build --platform=linux/amd64 -t poplar_rust .
#   Run:    docker run --rm --platform=linux/amd64 \
#             -v "$(pwd)/output:/project/output" poplar_rust
#
# The analysis takes exactly two input files, both shipped in the image:
#   Table_S1.csv          genotypes and metadata for the 2,122 individuals
#   tree_nj_boot1000.rds  neighbour-joining tree, 1,000 bootstrap replicates,
#                         precomputed on a compute server (see README.md)
# Everything else under /project/output is generated by the run.
#
# A pre-built image is published automatically to the GitHub Container Registry:
#   docker pull ghcr.io/ammarabdalrahem/poplar_rust:latest
#
# ---------------------------------------------------------------------------
# Base image
# ---------------------------------------------------------------------------
# rocker/geospatial:4.4.1 pins R 4.4.1 together with the full geospatial stack
# (GDAL / GEOS / PROJ, sf, terra, stars) and the tidyverse, all precompiled.
# This is the environment the PCI data editor used to verify the analysis, so
# the container reproduces that review setup exactly.
#
# --platform=linux/amd64 is required, not optional. The rocker images are
# published for linux/amd64 only, so on an Apple Silicon Mac (M1/M2/M3/M4) the
# build otherwise fails at this line with "no matching manifest for
# linux/arm64/v8". Pinning the platform also means the image is byte-identical
# whoever builds it - on a Mac, on an Intel machine, or in GitHub Actions - so
# the environment really is the same one used to produce the published results.
# On Apple Silicon the container runs under Rosetta emulation and is slower.
FROM --platform=linux/amd64 rocker/geospatial:4.4.1

LABEL org.opencontainers.image.source="https://github.com/ammarabdalrahem/poplar_rust"
LABEL org.opencontainers.image.description="Reproducible population-genetics workflow for Melampsora larici-populina (microsatellite markers)."
LABEL org.opencontainers.image.licenses="CC-BY-4.0"

ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /project

# ---------------------------------------------------------------------------
# Reproducibility: freeze CRAN to a dated Posit Package Manager snapshot
# ---------------------------------------------------------------------------
# Every build then resolves to the SAME package versions, and pulls precompiled
# binaries for the image's Ubuntu release (fast, no source compilation).
# Bump PKG_SNAPSHOT only when you deliberately want newer packages.
ARG PKG_SNAPSHOT=2025-04-15
RUN . /etc/os-release && \
    echo "options(repos = c(CRAN = 'https://packagemanager.posit.co/cran/__linux__/${VERSION_CODENAME}/${PKG_SNAPSHOT}'))" \
      >> /usr/local/lib/R/etc/Rprofile.site

# ---------------------------------------------------------------------------
# System libraries not already present in the geospatial base image
# ---------------------------------------------------------------------------
#   libglpk-dev : graph optimisation used by igraph / poppr
#   libgsl-dev  : GNU Scientific Library used by some genetics dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
      libglpk-dev libgsl-dev \
    && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------------------------
# CRAN packages  (sf, terra and the tidyverse are already in the base image)
# ---------------------------------------------------------------------------
RUN install2.r --error --skipinstalled -n -1 \
      knitr readxl cowplot viridis ggrepel ggsci scales \
      factoextra svglite reshape2 ggpubr RColorBrewer ggforce \
      rnaturalearth rnaturalearthdata mapdata mapplots \
      lme4 genepop hierfstat adegenet poppr pegas ape ade4 \
      BiocManager remotes

# ---------------------------------------------------------------------------
# Bioconductor  (pinned to release 3.20, the release paired with R 4.4)
# ---------------------------------------------------------------------------
RUN Rscript -e "BiocManager::install(version = '3.20', ask = FALSE, update = FALSE)" && \
    Rscript -e "BiocManager::install(c('ggtree', 'ggtreeExtra'), ask = FALSE, update = FALSE)"

# ---------------------------------------------------------------------------
# GitHub packages
# ---------------------------------------------------------------------------
# rnaturalearthhires is pinned to an exact commit for full reproducibility.
RUN Rscript -e "remotes::install_github('ropensci/rnaturalearthhires@e4736f636baa1c013d77d2ba028dd5bc334defee', upgrade = 'never')"

# RClone is a stable, rarely-updated package. For strict reproducibility, append
# a commit SHA to the ref below, e.g. 'dbailleul/RClone@<commit-sha>'.
RUN Rscript -e "remotes::install_github('dbailleul/RClone', dependencies = FALSE, upgrade = 'never')"

# ---------------------------------------------------------------------------
# Project files
# ---------------------------------------------------------------------------
# Two data inputs, read by the script at its working directory /project:
#   Table_S1.csv         -> read_csv("Table_S1.csv")
#   tree_nj_boot1000.rds -> readRDS("tree_nj_boot1000.rds")   [Figure 3]
# The bootstrap tree is precomputed because poppr::aboot with 1,000 replicates
# is too slow to run inside the container; the call that produced it is kept,
# commented out, next to the readRDS line in the script.
COPY Table_S1.csv             /project/Table_S1.csv
COPY tree_nj_boot1000.rds     /project/tree_nj_boot1000.rds

# Analysis code (identical to data_analysis_mlp.Rmd, without the knitr wrapper)
COPY data_analysis_mlp_new.R  /project/data_analysis_mlp_new.R

# Results are written under /project/output. Mount a host directory there to
# collect figures and tables on the host, e.g.:
#   docker run --rm -v "$(pwd)/output:/project/output" ghcr.io/ammarabdalrahem/poplar_rust:latest
VOLUME ["/project/output"]

CMD ["Rscript", "data_analysis_mlp_new.R"]
